# Generated by Django 3.1.6 on 2021-02-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveIntegerField()),
            ],
        ),
    ]
